### ISSUE TITLE
error :/ - help me !

### ISSUE THREAD

**Issue by finngod** [CodingGay/BlackObfuscator-ASPlugin#1]
An exception occurred applying plugin request [id: 'top.niunaijun.blackobfuscator']
> Failed to apply plugin 'top.niunaijun.blackobfuscator'.
   > Could not get unknown property 'compile' for configuration container of type org.gradle.api.internal.artifacts.configurations.DefaultConfigurationContainer.

**Comment by nnjun** [comment]
see https://stackoverflow.com/questions/69044250/build-gradle-error-could-not-get-unknown-property-compile

**Comment by nnjun** [comment]
hi, use 2.5 version, can work, use 2.5 version, can work
