### ISSUE TITLE
Not Work !!!!!!!

### ISSUE THREAD

**Issue by dfdfdfs** [CodingGay/BlackObfuscator-ASPlugin#15]
A problem occurred configuring root project 'File Picker Example'.
> Could not resolve all artifacts for configuration ':classpath'.
   > Could not find com.github.CodingGay:BlackObfuscator-ASPlugin:3.7.
     Searched in the following locations:
       - https://dl.google.com/dl/android/maven2/com/github/CodingGay/BlackObfuscator-ASPlugin/3.7/BlackObfuscator-ASPlugin-3.7.pom
       - https://jcenter.bintray.com/com/github/CodingGay/BlackObfuscator-ASPlugin/3.7/BlackObfuscator-ASPlugin-3.7.pom
       - file:/D:/test 5/test/ https:/jitpack.io /com/github/CodingGay/BlackObfuscator-ASPlugin/3.7/BlackObfuscator-ASPlugin-3.7.pom
     Required by:
         project :

**Comment by nnjun** [comment]
Step 1. Configure your build.gradle (in top level directory)
repositories {
    ...
    maven { url 'https://jitpack.io' }
}
