### ISSUE TITLE
error

### ISSUE THREAD

**Issue by testingnic** [CodingGay/BlackObfuscator-ASPlugin#2]
A problem occurred configuring root project 'aaaaa'.
> Could not resolve all artifacts for configuration ':classpath'.
   > Could not find com.github.CodingGay:BlackObfuscator-ASPlugin:2.8.
     Searched in the following locations:
       - https://repo.maven.apache.org/maven2/com/github/CodingGay/BlackObfuscator-ASPlugin/2.8/BlackObfuscator-ASPlugin-2.8.pom
       - https://jcenter.bintray.com/com/github/CodingGay/BlackObfuscator-ASPlugin/2.8/BlackObfuscator-ASPlugin-2.8.pom
       - https://dl.google.com/dl/android/maven2/com/github/CodingGay/BlackObfuscator-ASPlugin/2.8/BlackObfuscator-ASPlugin-2.8.pom
       - https://maven.fabric.io/public/com/github/CodingGay/BlackObfuscator-ASPlugin/2.8/BlackObfuscator-ASPlugin-2.8.pom
       - https://branchlock.net/android/com/github/CodingGay/BlackObfuscator-ASPlugin/2.8/BlackObfuscator-ASPlugin-2.8.pom
       - https://plugins.gradle.org/m2/com/github/CodingGay/BlackObfuscator-ASPlugin/2.8/BlackObfuscator-ASPlugin-2.8.pom
     Required by:
         project :

Possible solution:
 - Declare repository providing the artifact, see the documentation at https://docs.gradle.org/current/userguide/declaring_repositories.html

**Comment by nnjun** [comment]
repositories {
    ...
    maven { url 'https://jitpack.io' }
}

**Comment by testingnic** [comment]
@nnjun  a question this in some string obfuscator?

**Comment by nnjun** [comment]
No, please check here: https://github.com/CodingGay/BlackObfuscator/blob/main/README_EN.md
