### ISSUE TITLE
当bute[]数据到达一定数量的时候,解密数据不准确

### ISSUE THREAD

**Issue by binbin594738977** [CodingGay/BlackObfuscator-ASPlugin#25]
当bute[]数据长度到达一定数量的时候byte数据会加密成字符串展现到代码里面,通过此方法->$private static byte[] $d2j$hex$89788d37$decode_B(String src)还原, 目前发现还原的byte数据不准确, byte[]的长度没有到达一定数量时, 不会加密, 所以不会有问题

**Comment by nnjun** [comment]
这应该是dex2jar的问题：
https://github.com/pxb1988/dex2jar/pull/541
