### ISSUE TITLE
混淆规则能否加一个白名单？

### ISSUE THREAD

**Issue by ksxkq** [CodingGay/BlackObfuscator-ASPlugin#4]
BlackObfuscator {
    // 是否启用
    enabled true
    // 混淆深度
    depth 2
    // 需要混淆的类(匹配前面一段)
    obfClass = ["top.niunaijun", "com.abc"]
}

能否在混淆规则里面加一个白名单，指定某个 package 或者 class 不混淆？感谢

**Comment by nnjun** [comment]
已在计划中

**Comment by nnjun** [comment]
已更新 3.2，支持黑白名单。请看readme
