### ISSUE TITLE
This gradle version is not applicable.

### ISSUE THREAD

**Issue by Martin102000** [CodingGay/BlackObfuscator-ASPlugin#5]
This gradle version is not applicable. Please submit issues in https://github.com/CodingGay/BlackObfuscator-ASPlugin

  dependencies {
        classpath 'com.android.tools.build:gradle:7.0.4'
        classpath "com.github.CodingGay:BlackObfuscator-ASPlugin:3.2"

**Comment by nnjun** [comment]
Please clean and rebuild and provide a complete build log.
