### ISSUE TITLE
插件配置建议

### ISSUE THREAD

**Issue by Vove7** [CodingGay/BlackObfuscator-ASPlugin#7]
作者你好，这里在使用中发现插件是在 `project.afterEvaluate` 进行处理

希望能够在执行期间再进行配置，这是方便针对 `release` 和 `debug` 开动态开启 `BlackObfuscator.enable`

或有其他方式还请告知  thanks for your work :)

**Comment by nnjun** [comment]
在app的gradle中增加如下方法

`
boolean isReleaseBuildType() {
    for(String s : gradle.startParameter.taskNames) {
        s = s.toLowerCase()
        if (s.contains("release")) {
            return true
        }
    }
    return false
}

BlackObfuscator {
    enabled isReleaseBuildType()
    depth 2
    obfClass = ["com.speed.shadowsocks", "com.speed.markdown"]
}
`
